INSERT INTO MOVIES (movietitle,directors,genre,starrating,year,reviews) VALUES ('Harry Potter and the Deathly Hallows','David Yates','Fantasy',4.8,2010,'Awesome')
INSERT INTO MOVIES (movietitle,directors,genre,starrating,year,reviews) VALUES ('Executive Decision','Stuart Baird','Thriller',4.9,1996,'Wonderful!')
INSERT INTO MOVIES (movietitle,directors,genre,starrating,year,reviews) VALUES ('Quantico','Joshua Safran','Drama Thriller',4.5,2015,'Good story!')
INSERT INTO MOVIES (movietitle,directors,genre,starrating,year,reviews) VALUES ('Game of Thrones','Woody Allen','Thriller',4.7,2011,'Must watch')
INSERT INTO MOVIES (movietitle,directors,genre,starrating,year,reviews) VALUES ('Friends','James BUrrows','Comedy',4.6,1994,'Funny show')
INSERT INTO REVIEW (movieid,star,review) VALUES (1,'4.6','Very good!')
INSERT INTO REVIEW (movieid,star,review) VALUES (1,'4.8','Must watch movie @Harry!')
INSERT INTO REVIEW (movieid,star,review) VALUES (1,'4.7','Dialogues were damn!')
INSERT INTO REVIEW (movieid,star,review) VALUES (2,'4.6','Very good !')
INSERT INTO REVIEW (movieid,star,review) VALUES (2,'4.8','Must watch movie @Decision!')
INSERT INTO REVIEW (movieid,star,review) VALUES (2,'4.7','Dialogues were damn!')
INSERT INTO REVIEW (movieid,star,review) VALUES (3,'4.6','Very good!')
INSERT INTO REVIEW (movieid,star,review) VALUES (3,'4.8','Must watch movie @Quantico!')
INSERT INTO REVIEW (movieid,star,review) VALUES (3,'4.7','Dialogues were damn!')
INSERT INTO REVIEW (movieid,star,review) VALUES (4,'4.6','Very good!')
INSERT INTO REVIEW (movieid,star,review) VALUES (4,'4.8','Must watch movie @GOT!')
INSERT INTO REVIEW (movieid,star,review) VALUES (4,'4.7','Dialogues were damn!')
INSERT INTO REVIEW (movieid,star,review) VALUES (5,'4.6','Very good!')
INSERT INTO REVIEW (movieid,star,review) VALUES (5,'4.8','Must watch movie @Friends!')
INSERT INTO REVIEW (movieid,star,review) VALUES (5,'4.7','Dialogues were damn!')